#!/usr/bin/env python3
"""ip-thor-without-ayn-key.py <50-ayn_thor.yaml> <output>
Write the AYN Thor InputPlumber device config without its gpio-keys-ayn
source, so InputPlumber leaves the AYN button alone and
sm8550-thor-backlightd can grab it (the button shows the bottom-screen
dashboard; screenshots stay on Steam + R1). The output goes in
/etc/inputplumber/devices.d, which overrides the same file name in
/usr/share. Fails loudly if the upstream layout changes."""
import sys

src, dst = sys.argv[1], sys.argv[2]
lines = open(src).read().splitlines(keepends=True)
out, i, removed = [], 0, 0
while i < len(lines):
    line = lines[i]
    if line.startswith("  - ") and not line.startswith("  - -"):
        j = i + 1
        while j < len(lines) and lines[j].startswith("    "):
            j += 1
        block = lines[i:j]
        if any(b.strip() == "name: gpio-keys-ayn" for b in block):
            removed += 1
            i = j
            continue
    out.append(line)
    i += 1
if removed != 1:
    sys.exit(f"{src}: expected one gpio-keys-ayn source, found {removed}")
header = "# Generated by ip-thor-without-ayn-key.py: gpio-keys-ayn removed so\n# sm8550-thor-backlightd owns the AYN button.\n"
open(dst, "w").write(header + "".join(out))
